version: '3.8'

services:
  stream-integration-test:
    image: ${LOCAL_IMAGE_NAME}
    environment:
      - PREDICTIONS_STREAM_NAME=ride_predictions
      - RUN_ID=Test123
      - MODEL_LOCATION=/app/model
      - TEST_RUN=True
    volumes:
      - "./model:/app/model"
    ports:
      - "8080:8080"
    networks:
      - app-networks

networks:
  app-networks:
    name: app-networks
    external: true